apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tan-dara9280-darareact-certificate
  namespace: tan-dara9280-darareact
spec:
  secretName: tan-dara9280-darareact-secret-tls
  commonName: tan-dara9280-darareact.assessify.org
  dnsNames:
  - tan-dara9280-darareact.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
